fixup f2fs: fix to avoid memory leakage in f2fs_listxattr
 - This reverts Ben Hutchings' change to still use f2fs_err() instead of f2fs_msg() to avoid implicit error.

../fs/f2fs/xattr.c:587:4: error: implicit declaration of function 'f2fs_msg' [-Werror,-Wimplicit-function-declaration]
                        f2fs_msg(dentry->d_sb, KERN_ERR,
                        ^
1 error generated.

fixes: ed523cbd {"f2fs: fix to avoid memory leakage in f2fs_listxattr"}
Change-Id: I69f28c2b208cf29e90c7d2713a1826e2d0d9b168